### PR TITLE
Ecosystem integration

### LINKED ISSUE #62: Add the integration to Qiskit Ecosystem
### What is the expected behavior?
It could be usefull to already have the config file ready in order to add the project to the Qiskit Ecosystem from the beginning.
--> [docs](https://github.com/qiskit-community/ecosystem/blob/main/docs/project_overview.md#ecosystem-test-configuration)

#### Detailes
- Add `ecosystem.json` config file (⚠️ python version as 3.9 or 3.10 ?)
- Add json lint in tox (and Actions + Travis)
- Update [glossary](https://github.com/qiskit-community/quantum-prototype-template/blob/main/docs/file-map-and-description.md)

### PR DESCRIPTION
**Pull request by mickahell**
### Summary
Adding the config file for the integration of the project into the Qiskit Ecosystem.

### Details and comments
- [x] Add `ecosystem.json` config file
- [x] Add json lint in tox (and Actions + Travis)
- [x] Update [glossary](https://github.com/qiskit-community/quantum-prototype-template/blob/main/docs/file-map-and-description.md)

---
Closes #62

### CODE REVIEW

**Comment by mickahell** [comment]
@caleb-johnson, @garrison this should do the job :) if one of you can review it :)

FYI I set the python version at 3.9, that's the python version of the prototype project. It can be any version of python as long as it's support by Qiskit.

**Comment by caleb-johnson** [comment]
> @caleb-johnson, @garrison this should do the job :) if one of you can review it :)
> 
> FYI I set the python version at 3.9, that's the python version of the prototype project. It can be any version of python as long as it's support by Qiskit.

Thanks for submitting, this looks good.

@IceKhan13 could you please take a look at this?

**Comment by IceKhan13** [comment]
Looks great! :)

**Comment by IceKhan13** [comment]
@mickahell you are a rock star!

**Comment by mickahell** [comment]
I see the problem in the CI, I'm correcting it

**Comment by mickahell** [comment]
Seems I need your approval @IceKhan13 for running the CI

**Comment by caleb-johnson** [comment]
> Seems I need your approval @IceKhan13 for running the CI The tox works for me in local.

Looks like it passed this time. Looks great, thanks

**Comment by mickahell** [comment]
> > Seems I need your approval @IceKhan13 for running the CI The tox works for me in local.
> 
> Looks like it passed this time. Looks great, thanks

Yes, just an executable path issue ^^'
Sure your welcome :)

**Pull request merged**
